apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-live-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiktok-live-runner
  template:
    metadata:
      labels:
        app: tiktok-live-runner
    spec:
      containers:
        - name: tiktok-live-runner
          image: marongt123/jamming-minecraft-stream:tiktok
          imagePullPolicy: Always
          volumeMounts:
            - name: access-config
              mountPath: /app/config
      volumes:
        - name: access-config
          configMap:
            name: access-config
